### PR TITLE
optimization of wordwrap function

### PR DESCRIPTION
**Pull request by Tieske**

### CODE REVIEW

**Comment by amireh** [comment]
Hey @Tieske should we integrate this in the 3.0 changes?

**Comment by Tieske** [comment]
that makes sense.

**Comment by Tieske** [comment]
let's close this.

**Comment by amireh** [comment]
I think we did integrate the change but not the PR, I'm double-checking now.

**Comment by amireh** [comment]
@Tieske I've just integrated the change and published `3.0-2` with it. Thanks so much and my sincere apologies for missing this one.

**Comment by Tieske** [comment]
np was minor anyway. I checked the merge conflict and didn't find it worthwhile to fix it. So thanks for doing the dirty work for me 😄

**Pull request closed without merging**
